sonar.projectKey=luosicx_Bookkeeping
sonar.organization=luosicx

sonar.sources=Bookkeeping
sonar.tests=BookkeepingTests,BookkeepingUITests
sonar.exclusions=**/Resources/**,**/*.generated.swift

sonar.sourceEncoding=UTF-8
sonar.lang.swift.swiftlint.reportPaths=swiftlint-report.json

sonar.swift.version=5.9
sonar.swift.target=Bookkeeping
